# Generated by Django 5.1.2 on 2024-10-31 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='content')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.folder', verbose_name='folder')),
            ],
            options={
                'unique_together': {('content', 'folder')},
            },
        ),
    ]
